### ISSUE TITLE
Error: Invalid high padding size

### ISSUE THREAD

**Issue by pwichmann** [Blaizzy/mlx-vlm#102] opened 2024-10-22 19:59 UTC
What could explain the following error? All I had was an input image and a prompt based on a Qwen2 example here. Nothing fancy. Is there a maximum image size? My image was scaled down to (891, 1260) before feeding it in.

> [...]/mlx_vlm/models/qwen2_vl/qwen2_vl.py", line 82, in _merge_input_ids_with_image_features
>     image_features = mx.pad(image_features, ((0, 0), (0, pad_size), (0, 0)))
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: Invalid high padding size (-1389) passed to pad for axis 1. Padding sizes must be non-negative
> 
> Invalid high padding size (-1389) passed to pad for axis 1. Padding sizes must be non-negative

**Comment by Blaizzy** [comment] 2024-10-22 21:42
This happens because the image tokens where not passed on the prompt.

Could you share the reproducible code example?

**Comment by pwichmann** [comment] 2024-10-22 22:10
It is very simple:

I am using the image_load from mlx_vlm.utils. I can successfully display the image:

![image](https://github.com/user-attachments/assets/d58faca6-d39c-47ff-897c-f025e201b0ca)

This then already fails (I played around with the max_tokens; that is why they are high at the moment):

![image](https://github.com/user-attachments/assets/65055cc1-fb97-4982-8c1d-63d85f31226f)

**Comment by pwichmann** [comment] 2024-10-22 22:12
```python
import random
import os

from mlx_vlm import load, apply_chat_template, generate
from mlx_vlm.utils import load_image


# Load model and processor
qwen_vl_model, qwen_vl_processor = load("mlx-community/Qwen2-VL-7B-Instruct-4bit")
qwen_vl_config = qwen_vl_model.config

# Load PDF as image
# Get a random image from sample_pngs
random_image = random.choice(os.listdir("./sample_pngs_downscaled"))

image = load_image(f"./sample_pngs_downscaled/{random_image}")

messages = [
    {"role": "system", "content": "You are an expert at extracting text from images. Format your response in json."},
    {"role": "user", "content": "Extract the required client number from the image. Note that the image may contain German, English or French language."}
]

# Apply chat template
prompt = apply_chat_template(qwen_vl_processor, qwen_vl_config, messages)

# Generate text
import traceback    
try:
    qwen_vl_output = generate(
        qwen_vl_model,
        qwen_vl_processor,
        image,
        prompt,
        max_tokens=10000,
        temperature=0.7,
    )
    print(qwen_vl_output)
except Exception as e:
    print(traceback.format_exc())
    print(e)
```

**Comment by Blaizzy** [comment] 2024-10-22 22:29
I see, please install from source.

I came across this issue and merged a fix for it alongside the examples notebooks.

**Comment by pwichmann** [comment] 2024-10-23 08:16
Thank you for the prompt response (pun intended).

**Closed** 2024-10-23 08:31 UTC

**Comment by Blaizzy** [comment] 2024-10-23 09:36
My pleasure! 

Lucky I already had the response cached 😜
